dummysmtpd: don't die on client connection errors
The connection refused error in test-patchbomb-tls.t[1] is sporadic, but one of
the more often seen errors on Windows.  I added enough logging to a file and
dumped it out at the end to make the following observations:

  - The listening socket is successfully created and bound to the port, and the
    "listening at..." message is always logged.

  - Generally, the following is the entire log output, with the "accepted ..."
    message having been added after `sslutil.wrapserversocket`:

          listening at localhost:$HGPORT
          $LOCALIP ssl error
          accepted connect
          accepted connect
          $LOCALIP from=quux to=foo, bar
          $LOCALIP ssl error

  - In the cases that fail, asyncore.loop() in the run() method is exiting, but
    not with an exception.

  - In the cases that fail, the following is logged right after "listening ...":

        Traceback (most recent call last):
          File "c:\\Python27\\lib\\asyncore.py", line 83, in read
            obj.handle_read_event()
          File "c:\\Python27\\lib\\asyncore.py", line 443, in handle_read_event
            self.handle_accept()
          File "../tests/dummysmtpd.py", line 80, in handle_accept
            conn = sslutil.wrapserversocket(conn, ui, certfile=self._certfile)
          File "..\\mercurial\\sslutil.py", line 570, in wrapserversocket
            return sslcontext.wrap_socket(sock, server_side=True)
          File "c:\\Python27\\lib\\ssl.py", line 363, in wrap_socket
            _context=self)
          File "c:\\Python27\\lib\\ssl.py", line 611, in __init__
            self.do_handshake()
          File "c:\\Python27\\lib\\ssl.py", line 840, in do_handshake
            self._sslobj.do_handshake()
        error: [Errno 10054] $ECONNRESET$

  - If the base class handler is overridden completely, the the first "ssl
    error" line is replaced by the stacktrace, but the other lines are
    unchanged.  The client behaves no differently, whether or not the server
    stacktraced.

In general, `./run-tests.py --local -j9 -t9000 test-patchbomb-tls.t
--runs-per-test 20` would show the issue after a run or two.  With this change,
`./run-tests.py --local -j9 -t9000 test-patchbomb-tls.t --loop` ran 800 times
without a hiccup.  This makes me wonder if the other connection refused messages
that bubble up on occasion are caused by a similar issue.  It seems a bit
drastic to kill the whole server on account of a single communication failure
with a client.

# no-check-commit because of handle_error()

[1] https://buildbot.mercurial-scm.org/builders/Win7%20x86_64%20hg%20tests/builds/421/steps/run-tests.py%20%28python%202.7.13%29/logs/stdio