git: initialize `extra` to have at least the branch name for nullid
Otherwise, this crashes trying to convert to local encoding:

    ...
      File "/mnt/c/Users/Matt/hg/mercurial/logcmdutil.py", line 333, in _show
        branch = ctx.branch()
      File "/mnt/c/Users/Matt/hg/mercurial/context.py", line 675, in branch
        return encoding.tolocal(self._changeset.extra.get(b"branch"))
      File "/mnt/c/Users/Matt/hg/mercurial/encoding.py", line 181, in tolocal
        if isasciistr(s):
    TypeError: a bytes-like object is required, not 'NoneType'

This was originally reported to the thg bug tracker.

https://foss.heptapod.net/mercurial/tortoisehg/thg/-/issues/5629

Differential Revision: https://phab.mercurial-scm.org/D10528

--HG--
branch : stable